### ISSUE TITLE
Install icepyx library

### ISSUE THREAD

**Issue by scottyhq** [ICESAT-2HackWeek/jupyter-image-2020#2]
Currently getting an error trying to install icepyx with pip:

https://github.com/ICESAT-2HackWeek/jupyter-image-2020/blob/168137f8810d701f83cd1861a5cf13da8470b087/binder/environment.yml#L75-L76

Error:
```
2020-02-12T21:14:04.8985745Z Pip subprocess error:
2020-02-12T21:14:04.8986187Z   Running command git clone -q https://github.com/icesat2py/icepyx.git /tmp/pip-req-build-trhqfdza
2020-02-12T21:14:04.8986354Z     ERROR: Command errored out with exit status 1:
2020-02-12T21:14:04.8987099Z      command: /srv/conda/envs/notebook/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-trhqfdza/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-trhqfdza/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-trhqfdza/pip-egg-info
2020-02-12T21:14:04.8987504Z          cwd: /tmp/pip-req-build-trhqfdza/
2020-02-12T21:14:04.8987634Z     Complete output (5 lines):
2020-02-12T21:14:04.8987760Z     Traceback (most recent call last):
2020-02-12T21:14:04.8989507Z       File "<string>", line 1, in <module>
2020-02-12T21:14:04.8990148Z       File "/tmp/pip-req-build-trhqfdza/setup.py", line 3, in <module>
2020-02-12T21:14:04.8990319Z         with open("README.md", "r") as fh:
2020-02-12T21:14:04.8990695Z     FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
2020-02-12T21:14:04.8991023Z     ----------------------------------------
2020-02-12T21:14:04.8991171Z ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

 @JessicaS11
it looks like this is because your setup.py has `README.md` but your repo has `README.rst`
https://github.com/icesat2py/icepyx/blob/master/setup.py#L3

**Comment by JessicaS11** [comment]
Good catch. I just switched over to the .rst README earlier this week, and I forgot to update the setup.py file. I just updated it on the master branch.

**Comment by scottyhq** [comment]
closed by https://github.com/ICESAT-2HackWeek/jupyter-image-2020/commit/eb03a0a68db6c87525448c307dbf9e3bbe4e9ef3
